In [2]:
# Create some tensors
import torch

t0 = torch.tensor(1000)                  # 0-D Tensor
t1 = torch.tensor([9, 8, 7, 6])          # 1-D Tensor
t2 = torch.tensor([[1, 2, 3], [7, 5, 3]])  # 2-D Tensor

print(t0)
print(t1)
print(t2)

tensor(1000)
tensor([9, 8, 7, 6])
tensor([[1, 2, 3],
        [7, 5, 3]])


In [3]:
# set tensor data type
a = torch.ones((2, 3), dtype=torch.int16) # 2 rows 3 columns
print(a)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [4]:
 # cast to a different data type
b = a.to(dtype=torch.float32)
print(b)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [5]:
# check size
print(t1.size())
print(t2.shape)

torch.Size([4])
torch.Size([2, 3])


In [6]:
# check dimensionality
print(t1.ndimension())
print(t2.ndim)

1
2
